name: Cachegrind

on: pull_request

env:
  FILE_STR: test-input.txt
  FILE_MAIN: src/main.cpp
  TEST_MAIN: tests/test-main.cpp
  FILES_STD: src/trim-scalar.cpp src/trim-stdsimd.cpp
  TESTS_STD: tests/test-trim-scalar.cpp tests/test-trim-stdsimd.cpp
  FILES_SSE2: src/trim-sse2.cpp
  TESTS_SSE2: tests/test-trim-sse2.cpp
  FILES_AVX2: src/trim-avx2.cpp
  TESTS_AVX2: tests/test-trim-avx2.cpp
  FILES_NEON: src/trim-neon.cpp
  TESTS_NEON: tests/test-trim-neon.cpp
  VLG_OPTIONS: --tool=cachegrind --cache-sim=yes
  CG_OPTIONS: --show=Dr --auto=no --threshold=1.0

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate test file
        run: |
          python3 .github/workflows/generator.py $FILE_STR

      - name: Upload test file
        uses: actions/upload-artifact@v4
        with:
          name: test-input
          path: $FILE_STR
          retention-days: 1 
  test-scalar-stdsimd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        run: sudo apt-get update && sudo apt-get install -y libboost-test-dev

      - name: Run tests
        run: |
          g++ -Isrc $FILES_STD $TESTS_STD $TEST_MAIN -o trim-test
          ./trim-test
  test-sse2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        run: sudo apt-get update && sudo apt-get install -y libboost-test-dev

      - name: Run tests
        run: |
          g++ -msse2 -Isrc $FILES_SSE2 $TESTS_SSE2 $TEST_MAIN -o trim-test
          ./trim-test
  test-avx2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        run: sudo apt-get update && sudo apt-get install -y libboost-test-dev

      - name: Run tests
        run: |
          g++ -mavx2 -Isrc $FILES_AVX2 $TESTS_AVX2 $TEST_MAIN -o trim-test
          ./trim-test
  test-neon:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        run: sudo apt-get update && sudo apt-get install -y libboost-test-dev

      - name: Run tests
        run: |
          g++ -march=armv8-a+simd -Isrc $FILES_NEON $TESTS_NEON $TEST_MAIN -o trim-test
          ./trim-test
  cachegrind-sse2:
    needs: [generate, test-scalar-stdsimd, test-sse2]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download test file
        uses: actions/download-artifact@v4
        with:
          name: test-input

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Build for x86 SSE2
        run: |
          g++ -O3 -msse2 $FILE_MAIN $FILES_STD $FILES_SSE2 -o trim_sse2_o3
          g++ -O0 -msse2 $FILE_MAIN $FILES_STD $FILES_SSE2 -o trim_sse2_o0

      - name: Run Cachegrind
        run: |
          valgrind $VLG_OPTIONS --cachegrind-out-file=cachegrind-sse2-o3.out ./trim_sse2_o3 $FILE_STR
          valgrind $VLG_OPTIONS --cachegrind-out-file=cachegrind-sse2-o0.out ./trim_sse2_o0 $FILE_STR

      - name: Upload Cachegrind Results
        uses: actions/upload-artifact@v4
        with:
          name: cachegrind-sse2
          path: cachegrind-sse2-*.out

  cachegrind-avx2:
    needs: [generate, test-scalar-stdsimd, test-avx2]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download test file
        uses: actions/download-artifact@v4
        with:
          name: test-input

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Build for x86 AVX2
        run: |
          g++ -O3 -mavx2 $FILE_MAIN $FILES_STD $FILES_AVX2 -o trim_avx2_o3
          g++ -O0 -mavx2 $FILE_MAIN $FILES_STD $FILES_AVX2 -o trim_avx2_o0

      - name: Run Cachegrind
        run: |
          valgrind $VLG_OPTIONS --cachegrind-out-file=cachegrind-avx2-o3.out ./trim_avx2_o3 $FILE_STR
          valgrind $VLG_OPTIONS --cachegrind-out-file=cachegrind-avx2-o0.out ./trim_avx2_o0 $FILE_STR

      - name: Upload Cachegrind Results
        uses: actions/upload-artifact@v4
        with:
          name: cachegrind-avx2
          path: cachegrind-avx2-*.out

  cachegrind-neon:
    needs: [generate, test-scalar-stdsimd, test-neon]
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Download test file
        uses: actions/download-artifact@v4
        with:
          name: test-input

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Build for ARM64 NEON
        run: |
          g++ -O3 -march=armv8-a+simd $FILE_MAIN $FILES_STD $FILES_NEON -o trim_neon_o3
          g++ -O0 -march=armv8-a+simd $FILE_MAIN $FILES_STD $FILES_NEON -o trim_neon_o0

      - name: Run Cachegrind
        run: |
          valgrind $VLG_OPTIONS --cachegrind-out-file=cachegrind-neon-o3.out ./trim_neon_o3 $FILE_STR
          valgrind $VLG_OPTIONS --cachegrind-out-file=cachegrind-neon-o0.out ./trim_neon_o0 $FILE_STR

      - name: Upload Cachegrind Results
        uses: actions/upload-artifact@v4
        with:
          name: cachegrind-neon
          path: cachegrind-neon-*.out
  result:
    needs: [cachegrind-sse2, cachegrind-avx2, cachegrind-neon]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Download all cachegrind results
        uses: actions/download-artifact@v4
        with:
          path: res/

      - name: Output Results SSE2
        run: |
          cg_annotate $CG_OPTIONS res/cachegrind-sse2/cachegrind-sse2-o3.out
          cg_annotate $CG_OPTIONS res/cachegrind-sse2/cachegrind-sse2-o0.out
      - name: Output Results AVX2
        run: |
          cg_annotate $CG_OPTIONS res/cachegrind-avx2/cachegrind-avx2-o3.out
          cg_annotate $CG_OPTIONS res/cachegrind-avx2/cachegrind-avx2-o0.out
      - name: Output Results NEON
        run: |
          cg_annotate $CG_OPTIONS res/cachegrind-neon/cachegrind-neon-o3.out
          cg_annotate $CG_OPTIONS res/cachegrind-neon/cachegrind-neon-o0.out
